version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: guardpath-postgres

    environment:
      POSTGRES_USER: guardpath
      POSTGRES_PASSWORD: guardpath
      POSTGRES_DB: guardpath_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
